name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 🔹 Tests (Dockerfile.dev)
      - name: Build test image
        run: docker build -t soussoudesire/react-test -f Dockerfile.dev .

      - name: Run tests
        run: docker run -e CI=true soussoudesire/react-test npm test

      # ❌ PLUS BESOIN de push Docker Hub pour Beanstalk AL2023

      # 🔹 Package complet du projet (IMPORTANT)
      - name: Create deployment package
        run: zip -r deploy.zip . -x "*.git*" "node_modules/*"

      # 🔹 Deploy
      - name: Deploy to Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: v-${{ github.sha }}
          region: ${{ secrets.AWS_REGION }}
          deployment_package: deploy.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}